### ISSUE TITLE
Additional Metrics

### ISSUE THREAD

**Issue by stevesloka** [heptio/gimbal#108]
**Is this a BUG REPORT, PERFORMANCE REPORT or FEATURE REQUEST?**:

Feature Request

Need additional metrics exposed via discoverer:

- upstream-services{cluster, tenant/namespace} -- (Number of upstream services, labeled by cluster and tenant/namespace)
- replicated-services{cluster, tenant/namespace} -- (Number of services replicated to gimbal cluster labeled by cluster and tenant/namespace)
- invalid-services{cluster, tenant/namespace} -- (Number of services unable to be replicated labeled by cluster and tenant/namespace)
- upstream-endpoints{cluster, tenant/namespace,service} -- (Number of endpoints - meaning IP:Port - in the upstream labeled by cluster, namespace, and service name)
- replicated-endpoints{cluster, tenant/namespace,service} -- (Number of endpoints - meaning IP:Port replicated to Gimbal cluster labeled by cluster, namespace and service name)
- invalid-endpoints{cluster, tenant/namespace,service} -- (Number of endpoints - meaning IP:Port - unable to be replicated to gimbal labeled by namespace and service name)

**Comment by rosskukulinski** [comment]
@stevesloka is this something you or @alexbrand should tackle?

I tried an alternative path to grab these metrics from kube-state-metrics, but the data isn't there (label breakdowns).

I would think this would be helpful data to have for #72.  Assigning to v0.3 milestone, but willing to discuss relative priorities to other in-progress issues.

**Comment by rosskukulinski** [comment]
`invalid-endpoints` would be any endpoints that are unable to be synced for whatever reason.  The only reason I can think of at this point is if Endpoints must follow the same valid DNS name as Services.

`upstream-services` is the number of all services (or LBaaS) that exist that could be discovered. 

`replicated-services` are the number of services/LBaaS that have been replicated/synchronized.  

`invalid-services` is the total count of services that are unable to be replicated/synced due to any reason (right now, this is most likely due to invalid name from DNS perspective.)

For any backend that's being discovered:
count(upstream-services) = count(replicated-services) + count(invalid-services)

**Comment by stevesloka** [comment]
Thanks for the clarification! This also means these metrics are type `gauge` rather than counter.

**Comment by rosskukulinski** [comment]
I would think `gauge` is the appropriate metric type.
